name: monolith
description: A project management library that supports the modular monolith structure for Flutter projects. It automates the setup of development environments and task execution for Flutter applications using the monolith.yaml configuration file.
version: 1.0.2
resolution: workspace
repository: https://github.com/eaglesakura/flutter_monolith

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  json_annotation: ^4.9.0
  freezed_annotation: ^3.0.0
  meta: ^1.16.0
  armyknife_yamlx: ^1.0.0
  path: ^1.9.1
  armyknife_logger: ^1.0.1
  dartx: ^1.2.0
  armyknife_dartx: ^1.0.0
  csv: ^6.0.0
  mustache_template: ^2.0.0
  collection: ^1.18.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.0
  build_runner: ^2.5.2
  freezed: ^3.0.6
  json_serializable: ^6.9.5
